title: Mikefeldmeier github
name: MFC Computing
# GFN  or  kramdown
markdown: kramdown
defaults:
  - 
    scope:
      path: "assets/images"
    values:
      image: true
sass:
      sass_dir: _sass
      style: compressed
webrick:
      headers:
        Cache-Control: no-cache
        Cache-Control: no-store
        Cache-Control: must-revalidate
        Pragma: no-cache
        Expires: 0
