title: Mikefeldmeier github
name: MFC Computing
email: mikos0102@cologne-engines.de
# link rel canonical {{ site.canonical }}
canonical: http://mikefeldmeier.github.io/
# google AMP pages
useamp: false
# GFN  or  kramdown
markdown: kramdown
defaults:
  - 
    scope:
      path: "assets/images"
    values:
      image: true
sass:
      sass_dir: _sass
      style: compressed
webrick:
      headers:
        Cache-Control: no-cache
        Cache-Control: no-store
        Cache-Control: must-revalidate
        Pragma: no-cache
        Expires: 0
